// 20 Kenyan Universities (10 public + 10 private) with representative programmes

export interface KenyaUniversity {
  id: string;
  name: string;
  shortName: string;
  type: 'public' | 'private';
  location: string;
  courses: string[];
}

export const KENYA_UNIVERSITIES: KenyaUniversity[] = [
  // ─── PUBLIC UNIVERSITIES ───────────────────────────────────────────────────
  {
    id: 'uon',
    name: 'University of Nairobi',
    shortName: 'UoN',
    type: 'public',
    location: 'Nairobi',
    courses: [
      'Bachelor of Medicine & Bachelor of Surgery (MBChB)',
      'Bachelor of Laws (LLB)',
      'Bachelor of Science in Computer Science',
      'Bachelor of Commerce (Accounting)',
      'Bachelor of Arts in Economics',
      'Bachelor of Science in Nursing',
      'Bachelor of Engineering (Civil)',
      'Bachelor of Pharmacy',
    ],
  },
  {
    id: 'kenyatta',
    name: 'Kenyatta University',
    shortName: 'KU',
    type: 'public',
    location: 'Nairobi',
    courses: [
      'Bachelor of Education (Arts)',
      'Bachelor of Education (Science)',
      'Bachelor of Business Administration',
      'Bachelor of Science in Information Technology',
      'Bachelor of Science in Biochemistry',
      'Bachelor of Arts in Communication',
      'Bachelor of Science in Environmental Science',
      'Bachelor of Science in Mathematics',
    ],
  },
  {
    id: 'moi',
    name: 'Moi University',
    shortName: 'MU',
    type: 'public',
    location: 'Eldoret',
    courses: [
      'Bachelor of Medicine & Bachelor of Surgery (MBChB)',
      'Bachelor of Science in Computer Science',
      'Bachelor of Laws (LLB)',
      'Bachelor of Science in Engineering (Electrical)',
      'Bachelor of Business & Entrepreneurship',
      'Bachelor of Science in Agriculture',
      'Bachelor of Science in Environmental Health',
      'Bachelor of Arts in Tourism & Hospitality',
    ],
  },
  {
    id: 'jkuat',
    name: 'Jomo Kenyatta University of Agriculture & Technology',
    shortName: 'JKUAT',
    type: 'public',
    location: 'Juja, Kiambu',
    courses: [
      'Bachelor of Science in Computer Science',
      'Bachelor of Science in Electrical & Electronic Engineering',
      'Bachelor of Science in Civil Engineering',
      'Bachelor of Science in Mechanical Engineering',
      'Bachelor of Science in Food Science & Technology',
      'Bachelor of Science in Agriculture',
      'Bachelor of Commerce',
      'Bachelor of Science in Actuarial Science',
    ],
  },
  {
    id: 'egerton',
    name: 'Egerton University',
    shortName: 'EU',
    type: 'public',
    location: 'Njoro, Nakuru',
    courses: [
      'Bachelor of Science in Agriculture',
      'Bachelor of Science in Environmental Science',
      'Bachelor of Science in Agricultural Economics',
      'Bachelor of Science in Food Nutrition & Dietetics',
      'Bachelor of Arts in Communication & Journalism',
      'Bachelor of Education (Arts)',
      'Bachelor of Science in Range Management',
      'Bachelor of Commerce',
    ],
  },
  {
    id: 'maseno',
    name: 'Maseno University',
    shortName: 'MasU',
    type: 'public',
    location: 'Maseno, Kisumu',
    courses: [
      'Bachelor of Science in Computer Science',
      'Bachelor of Education (Science)',
      'Bachelor of Science in Community Health',
      'Bachelor of Arts in Public Administration',
      'Bachelor of Science in Statistics',
      'Bachelor of Business Administration',
      'Bachelor of Arts in Sociology',
      'Bachelor of Science in Mathematics',
    ],
  },
  {
    id: 'dedan-kimathi',
    name: 'Dedan Kimathi University of Technology',
    shortName: 'DeKUT',
    type: 'public',
    location: 'Nyeri',
    courses: [
      'Bachelor of Science in Software Engineering',
      'Bachelor of Science in Electrical Engineering',
      'Bachelor of Science in Mechanical Engineering',
      'Bachelor of Science in Computer Science',
      'Bachelor of Science in Hospitality Management',
      'Bachelor of Commerce',
      'Bachelor of Science in Tourism Management',
      'Bachelor of Science in Actuarial Science',
    ],
  },
  {
    id: 'technical-university-kenya',
    name: 'Technical University of Kenya',
    shortName: 'TU-K',
    type: 'public',
    location: 'Nairobi',
    courses: [
      'Bachelor of Technology in Applied Biology',
      'Bachelor of Technology in Architecture',
      'Bachelor of Technology in Electrical Engineering',
      'Bachelor of Technology in Civil Engineering',
      'Bachelor of Technology in Information Technology',
      'Bachelor of Arts in Social Work',
      'Bachelor of Technology in Geospatial Engineering',
      'Bachelor of Technology in Pharmaceutical Technology',
    ],
  },
  {
    id: 'south-eastern',
    name: 'South Eastern Kenya University',
    shortName: 'SEKU',
    type: 'public',
    location: 'Kitui',
    courses: [
      'Bachelor of Science in Nursing',
      'Bachelor of Science in Computer Science',
      'Bachelor of Science in Agriculture',
      'Bachelor of Arts in Social Work',
      'Bachelor of Laws (LLB)',
      'Bachelor of Education (Science)',
      'Bachelor of Commerce',
      'Bachelor of Science in Environmental Science',
    ],
  },
  {
    id: 'laikipia',
    name: 'Laikipia University',
    shortName: 'LU',
    type: 'public',
    location: 'Nyahururu',
    courses: [
      'Bachelor of Education (Arts)',
      'Bachelor of Arts in Peace & Conflict Studies',
      'Bachelor of Science in Wildlife Management',
      'Bachelor of Business Administration',
      'Bachelor of Arts in Community Development',
      'Bachelor of Science in Information Technology',
      'Bachelor of Arts in Tourism',
      'Bachelor of Science in Mathematics',
    ],
  },

  // ─── PRIVATE UNIVERSITIES ──────────────────────────────────────────────────
  {
    id: 'strathmore',
    name: 'Strathmore University',
    shortName: 'SU',
    type: 'private',
    location: 'Nairobi',
    courses: [
      'Bachelor of Commerce (Accounting & Finance)',
      'Bachelor of Business Information Technology',
      'Bachelor of Laws (LLB)',
      'Bachelor of Science in Mathematics & Computer Science',
      'Bachelor of Arts in Journalism & Communication',
      'Bachelor of Science in Applied Computer Science',
      'Bachelor of Commerce (Marketing)',
      'Bachelor of Science in Actuarial Science',
    ],
  },
  {
    id: 'usiu',
    name: 'United States International University Africa',
    shortName: 'USIU',
    type: 'private',
    location: 'Nairobi',
    courses: [
      'Bachelor of Science in International Business Administration',
      'Bachelor of Science in Informatics & Computer Science',
      'Bachelor of Science in Communication',
      'Bachelor of Science in Psychology',
      'Bachelor of Arts in International Relations',
      'Bachelor of Science in Hospitality Management',
      'Bachelor of Commerce',
      'Bachelor of Science in Nursing',
    ],
  },
  {
    id: 'aga-khan',
    name: 'Aga Khan University',
    shortName: 'AKU',
    type: 'private',
    location: 'Nairobi',
    courses: [
      'Bachelor of Science in Nursing',
      'Bachelor of Medicine & Bachelor of Surgery (MBChB)',
      'Bachelor of Science in Medical Laboratory Sciences',
      'Bachelor of Science in Midwifery',
      'Master of Public Health',
      'Bachelor of Science in Health Informatics',
      'Bachelor of Science in Physiotherapy',
      'Diploma in Clinical Medicine',
    ],
  },
  {
    id: 'daystar',
    name: 'Daystar University',
    shortName: 'DU',
    type: 'private',
    location: 'Nairobi / Athi River',
    courses: [
      'Bachelor of Arts in Communication',
      'Bachelor of Arts in Peace & Diplomacy',
      'Bachelor of Science in Community Development',
      'Bachelor of Arts in International Studies',
      'Bachelor of Science in Business Administration',
      'Bachelor of Arts in Counselling Psychology',
      'Bachelor of Arts in Social Work',
      'Bachelor of Theology',
    ],
  },
  {
    id: 'catholic-university',
    name: 'Catholic University of Eastern Africa',
    shortName: 'CUEA',
    type: 'private',
    location: 'Nairobi',
    courses: [
      'Bachelor of Arts in Philosophy',
      'Bachelor of Laws (LLB)',
      'Bachelor of Science in Computer Science',
      'Bachelor of Commerce',
      'Bachelor of Education',
      'Bachelor of Arts in Religious Studies',
      'Bachelor of Science in Environmental Management',
      'Bachelor of Arts in Sociology',
    ],
  },
  {
    id: 'africa-nazarene',
    name: 'Africa Nazarene University',
    shortName: 'ANU',
    type: 'private',
    location: 'Ongata Rongai, Kajiado',
    courses: [
      'Bachelor of Science in Computer Science',
      'Bachelor of Business Administration',
      'Bachelor of Science in Nursing',
      'Bachelor of Arts in Communication',
      'Bachelor of Science in Environmental Science',
      'Bachelor of Arts in Social Work',
      'Bachelor of Education (Arts)',
      'Bachelor of Commerce',
    ],
  },
  {
    id: 'mount-kenya',
    name: 'Mount Kenya University',
    shortName: 'MKU',
    type: 'private',
    location: 'Thika, Kiambu',
    courses: [
      'Bachelor of Science in Nursing',
      'Bachelor of Pharmacy',
      'Bachelor of Science in Clinical Medicine',
      'Bachelor of Laws (LLB)',
      'Bachelor of Commerce',
      'Bachelor of Science in Information Technology',
      'Bachelor of Science in Nutrition & Dietetics',
      'Bachelor of Science in Medical Laboratory Sciences',
    ],
  },
  {
    id: 'presbyterian',
    name: 'Presbyterian University of East Africa',
    shortName: 'PUEA',
    type: 'private',
    location: 'Kikuyu, Kiambu',
    courses: [
      'Bachelor of Arts in Development Studies',
      'Bachelor of Science in Computer Science',
      'Bachelor of Arts in Communication',
      'Bachelor of Commerce',
      'Bachelor of Arts in Counselling Psychology',
      'Bachelor of Education',
      'Bachelor of Science in Information Technology',
      'Bachelor of Arts in Theology',
    ],
  },
  {
    id: 'kenya-methodist',
    name: 'Kenya Methodist University',
    shortName: 'KeMU',
    type: 'private',
    location: 'Meru',
    courses: [
      'Bachelor of Science in Nursing',
      'Bachelor of Science in Computer Science',
      'Bachelor of Commerce',
      'Bachelor of Science in Clinical Medicine',
      'Bachelor of Arts in Public Administration',
      'Bachelor of Science in Agriculture',
      'Bachelor of Arts in Communication',
      'Bachelor of Science in Environmental Science',
    ],
  },
  {
    id: 'pan-africa',
    name: 'Pan Africa Christian University',
    shortName: 'PAC',
    type: 'private',
    location: 'Nairobi',
    courses: [
      'Bachelor of Science in Business Administration',
      'Bachelor of Arts in Communication',
      'Bachelor of Arts in Leadership & Management',
      'Bachelor of Science in Information Technology',
      'Bachelor of Arts in Community Development',
      'Bachelor of Arts in Counselling Psychology',
      'Bachelor of Theology',
      'Bachelor of Arts in Education',
    ],
  },
];

export function getCourses(universityId: string): string[] {
  return KENYA_UNIVERSITIES.find((u) => u.id === universityId)?.courses ?? [];
}
